### ISSUE TITLE
Error with BARON

### ISSUE THREAD

**Issue by caovankien** [jump-dev/BARON.jl#12]
Hello everyone,

I'm a new user Julia. I would like to use BARON solver to solve my problem, but there is some error: 

![capture](https://user-images.githubusercontent.com/36992694/41544156-5d9c3c72-7318-11e8-8c9f-0bae29cb9396.PNG)

I tried to fix it, but still not.  Could you please help me solve it? thanks a lot.

**Comment by joehuchette** [comment]
What version of the packages are you using? ( Pkg.status() ). There may be an incompatibility between BARON.jl and MathProgBase.jl

**Comment by caovankien** [comment]
Here is the information about the packages that I use.
Thank you very much for your help.
julia> Pkg.status()
18 required packages:
 - AmplNLWriter                  0.4.0
 - Atom                          0.6.14
 - BARON                         0.3.1              9726059a (dirty)
 - CPLEX                         0.3.2
 - CSV                           0.2.5
 - CoinOptServices               0.3.0
 - DataFrames                    0.11.6
 - ExcelFiles                    0.5.0
 - ExcelReaders                  0.9.0
 - GR                            0.31.0
 - Gurobi                        0.4.0
 - Ipopt                         0.3.0
 - JLD                           0.8.3
 - JuMP                          0.18.2
 - KNITRO                        0.4.0
 - NamedArrays                   0.7.0
 - Plots                         0.17.2+            master
 - PyPlot                        2.5.0
88 additional packages:
 - ASTInterpreter2               0.1.1
 - AssetRegistry                 0.0.1
 - BinDeps                       0.8.8
 - BinaryProvider                0.3.2
 - Blink                         0.6.2
 - Blosc                         0.5.0
 - BufferedStreams               0.4.0
 - CMakeWrapper                  0.1.0
 - Calculus                      0.4.0
 - CategoricalArrays             0.3.10
 - Cbc                           0.3.2
 - Clp                           0.4.0
 - CodeTools                     0.5.0
 - CodecZlib                     0.4.3
 - ColorTypes                    0.6.7
 - Colors                        0.8.2
 - Combinatorics                 0.6.0
 - CommonSubexpressions          0.1.0
 - Compat                        0.69.0
 - Conda                         0.8.1
 - Contour                       0.4.0
 - DataStreams                   0.3.6
 - DataStructures                0.8.3
 - DataValues                    0.3.3
 - DebuggerFramework             0.1.2
 - DiffResults                   0.0.3
 - DiffRules                     0.0.4
 - Distances                     0.6.0
 - DocSeeker                     0.1.0
 - FileIO                        0.9.0
 - FixedPointNumbers             0.4.6
 - ForwardDiff                   0.7.5
 - HDF5                          0.9.2
 - Hiccup                        0.1.1
 - HttpCommon                    0.4.0
 - HttpParser                    0.3.1
 - HttpServer                    0.3.1
 - InternedStrings               0.6.2
 - IterTools                     0.2.1
 - IterableTables                0.7.1
 - IteratorInterfaceExtensions   0.0.2
 - JSON                          0.17.2
 - Juno                          0.4.1
 - LNR                           0.0.2
 - LaTeXStrings                  1.0.0
 - Lazy                          0.12.1
 - LegacyStrings                 0.3.0
 - LibExpat                      0.4.2
 - Libz                          0.2.4
 - LightXML                      0.6.0
 - MacroTools                    0.4.1
 - MathProgBase                  0.7.1
 - MbedTLS                       0.5.11
 - Measures                      0.2.0
 - Media                         0.3.0
 - Missings                      0.2.9
 - Mustache                      0.3.2
 - Mux                           0.3.0
 - NaNMath                       0.3.1
 - NamedTuples                   4.0.2
 - Nullables                     0.0.5
 - Parameters                    0.9.0
 - Pidfile                       1.0.0
 - PlotThemes                    0.2.0
 - PlotUtils                     0.4.4
 - Polynomials                   0.3.2
 - PyCall                        1.17.1
 - RecipesBase                   0.3.1
 - Reexport                      0.1.0
 - Requires                      0.4.4
 - ReverseDiffSparse             0.8.1
 - SHA                           0.5.7
 - Showoff                       0.2.0
 - SortingAlgorithms             0.2.1
 - SpecialFunctions              0.5.0
 - StaticArrays                  0.7.1
 - StatsBase                     0.23.0
 - StringDistances               0.2.1
 - TableShowUtils                0.0.2
 - TableTraits                   0.2.0
 - TableTraitsUtils              0.1.3
 - Tokenize                      0.4.2
 - TranscodingStreams            0.5.2
 - URIParser                     0.3.1
 - VersionParsing                1.1.1
 - WeakRefStrings                0.4.7
 - WebSockets                    0.5.0
 - WinRPM                        0.3.2

**Comment by joehuchette** [comment]
Why is BARON dirty? Have you made local changes?

**Comment by odow** [comment]
@joehuchette close as out-of-date?

**Comment by joaquimg** [comment]
Yes, this problem works smoothly nowadays
