### ISSUE TITLE
Minor bug?

### ISSUE THREAD

**Issue by sreekz** [jump-dev/BARON.jl#2]
Tests failed (on Windows) with Julia v0.4.7 and JuMP v0.14.1.
Line 188: unescape_string() was removing \ in file path causing error
ERROR: ArgumentError: \x used with no following hex digits in "opt:\"C:\Users\USER\AppData\Local\Temp\sum.lst\";"
 in print_unescaped at strings/io.jl:174
 in sprint at iostream.jl:206
 in unescape_string at strings/io.jl:209

Directly printing string without unescape_string() in line 188 fixed issue.
https://github.com/sreekz/BARON.jl/blob/patch-1/src/BARON.jl

Please verify and confirm fix.

**Comment by joaquimg** [comment]
Related to very old version. Does not appear in many tests. also `unescape_string` is not used anymore.
