### ISSUE TITLE
Results.jl missing `MOI`

### ISSUE THREAD

**Issue by selvi-aras** [jump-dev/BARON.jl#58]
Dear BARON.jl developers,

https://discourse.julialang.org/t/jump-baron/100401 
Here we realized that on line 17 of [results.jl](https://github.com/jump-dev/BARON.jl/blob/master/src/moi/results.jl) there is a missing `MOI.` on LOCALLY_SOLVED.

Thank you for your time!

**Comment by selvi-aras** [comment]
Thank you! I am actively using BARON.jl, I can flag more issues if I find out anything else.

**Comment by odow** [comment]
Tagged a new release, so should be ready in 20 minutes or so.

There are some known issues:
https://github.com/jump-dev/BARON.jl/blob/90ddf4343ff2351c8523959289db6a5e15d143f3/test/moi_test.jl#L33-L51

but they're mainly some edge cases, like having a variable with `[a, Inf)` as an Interval bound (cannot happen via JuMP).

**Comment by selvi-aras** [comment]
Thank you for letting me know! Also, `set_silent(model)` does not work with BARON -- shall I open a new issue for this or maybe I am missing something?

**Comment by odow** [comment]
I opened an issue: https://github.com/jump-dev/BARON.jl/issues/60

You can use `set_attribute(model, "PrLevel", 0)` instead for now.
