### ISSUE TITLE
Weird objective value output, when only a pre-processing solution is found

### ISSUE THREAD

**Issue by AnaConstantin** [jump-dev/BARON.jl#61]
Dear BARON.jl Team,

I have the following situation with a complex optimization-problem:

- During pre-processing a solution is found, with an objective value of (in this case) 133,26.
- Till the MaxTime is reached, no other solution is found.
- Calling "objective_value(jumpmodel)" after the optimization is done, gives the result 999999999999999993220948674361627976461708441944064.000000
- The solution values for the variables are however correct (the ones from the pre-processing).

Unfortunately due to IP-rights, I cannot provide the model, where I discovered this behaviour. However I hope a fix can be found without it.
The problem seems to come from here
 BARON.jl -> src->moi->results.jl at line 75 
"model.inner.solution_info.objective_value"
 

Best regards
Ana Constantin

**Comment by odow** [comment]
BARON.jl parses the objective value direct from the solution file written by BARON, so I don't know if there's much we can do, especially without a reproducible example.

https://github.com/jump-dev/BARON.jl/blob/90ddf4343ff2351c8523959289db6a5e15d143f3/src/util.jl#L294-L294

To debug, you could set `set_attribute(model, BARON..PrintInputFile(), true)`, and then look in the same directory for an output file and see what it says.

**Comment by AnaConstantin** [comment]
Hello, sorry for the late reply, I had some trouble finding a case that consistently leads to this weird result, since the last update reduced the number of such cases. 
I have looked into the tim.lst File and found this value at the position of the objective_value : 0.100000000000E+52.
So yes, it seems to be a BARON-Problem. Thank you for the suggestion where to look. I will take the problem up with the BARON support team.
