### ISSUE TITLE
How to specify BARON license

### ISSUE THREAD

**Issue by odow** [jump-dev/BARON.jl#69]
When i use BARON with the following errors:
```julia
       BARON version 23.12.16. Built: LNX-64 Sat Dec 16 20:54:13 EST 2023
      
       BARON is a product of The Optimization Firm.
       For information on BARON, see https://minlp.com/about-baron
       No BARON license file found in user PATH.  Continuing in demo mode.
       Model exceeds demo size (10 variables, 10 constraints, 50 nonlinearities)
       A valid BARON license is required for this model.
       BARON will exit now.
      
                                *** Licensing error *** 
```
so, how to set BARON license in which PATH?

thanks.

_Originally posted by @askuyue in https://github.com/jump-dev/BARON.jl/issues/30#issuecomment-1863782961_

**Comment by odow** [comment]
You need to obtain a license from The Optimization Firm: https://minlp.com/baron-licenses

When you obtain the license you should get instructions for where to put it, but it probably needs to go in the same folder as your BARON executable.

**Comment by askuyue** [comment]
Hi,
  firstly, thanks for your nice.

  I have obtained a license. But, i don't know that which path is the license putted such that Julia can read the license with BARON.jl.

  So, i want to ask how to set the PATH for Julia with BARON.

Thanks again.

**Comment by askuyue** [comment]
Yes, I got it.

Firstly,
```julia
        julia> pwd()
                "/home/YOUR_NAME/jlWorks"
```
Secondly, plese put your  baronlice.txt into /home/YOUR_NAME/jlWorks.

Finally, That's all.

**Comment by odow** [comment]
Great. I'll update the README: https://github.com/jump-dev/BARON.jl/pull/70
