### ISSUE TITLE
There is no semicolon (;) in the STARTING_POINT of FileName.bar  generated by Julia.

### ISSUE THREAD

**Issue by askuyue** [jump-dev/BARON.jl#76]
Hello, 

 Thanks very much for your working.

 Here, i want to pull a issue that there is no semicolon (;) in the STARTING_POINT of FileName.bar  generated by Julia. 

 Like this : 
STARTING_POINT{
x1: 5.0 
x2: 14.0 
x3: 1.3333333333333333 
}
 And you known this is wrong. The right is 
STARTING_POINT{
x1: 5.0;
x2: 14.0;
x3: 1.3333333333333333;
}

Thanks very much.

**Comment by askuyue** [comment]
BARON version 24.5.8

**Comment by odow** [comment]
Does BARON work, or does it throw an error?

**Comment by albesch1** [comment]
I also noticed this issue. The BARON devs said there should be a semicolon, but the parser wouldn't complain (it just seems to ignore the starting point). Once you add the semicolon, BARON promts feasiblity of the starting point during presolve.

**Comment by odow** [comment]
> but the parser wouldn't complain (it just seems to ignore the starting point)

Ah, I guess this is why the tests did not catch the issue :smile:

I will fix after https://github.com/jump-dev/BARON.jl/pull/78

**Comment by albesch1** [comment]
Much appreciated! ☺

**Comment by askuyue** [comment]
Thanks. Just throw the error in Line of STARTING_POINT. And it does not impact the results.
