### ISSUE TITLE
Can you add support for trigonometric functions sin(x), cos(x), etc in BARON.jl?

### ISSUE THREAD

**Issue by askuyue** [jump-dev/BARON.jl#77]
Thank you very much for all your hard work.

I have another need that I don't know if I can fulfill. In BARON's documentation, there is no support for trigonometric functions, could you please help to add support for trigonometric functions in BARON.jl? For example. sin， cos, or provide an idea for BARON to support these trigonometric functions?

Thank you very much.

**Comment by odow** [comment]
Hi @askuyue, 

Unfortunately, no.

See the BARON manual: https://minlp.com/downloads/docs/baron%20manual.pdf

![image](https://github.com/jump-dev/BARON.jl/assets/8177701/5acaa052-4a2c-4282-9150-7694c56a5448)

p.s., Please note that BARON.jl is not an official product of the Optimization Firm: https://github.com/jump-dev/BARON.jl?tab=readme-ov-file#affiliation. If you are a commercial customer and you have feature requests for BARON, you should reach out to their support team.

**Comment by askuyue** [comment]
Thanks.

 I'm very sorry, I was abrupt and shouldn't have asked such a cheap and stupid question.

**Comment by odow** [comment]
> I'm very sorry, I was abrupt and shouldn't have asked such a cheap and stupid question.

Don't be sorry. No question is a bad question :smile:

**Comment by boyogala** [comment]
hello, maybe BARON up to version of 1.0.0?

**Comment by odow** [comment]
https://minlp.com/baron-user-manual#Chx1.S6.SS1

<img width="1110" height="173" alt="Image" src="https://github.com/user-attachments/assets/94bbdbb9-c816-42ef-acc0-91b889571813" />
